### PR TITLE
"Redesign" info in WCCC card

### PR DESCRIPTION
**Pull request by Arevyn24**
- Give links to course info meaningful text
- Adjust spacing above and below some paragraphs to shorten length
- Move both course info links to the top so they'll be above the "Read More" link once everything is merged

### CODE REVIEW

**Comment by Arevyn24** [comment]
image

**Comment by ninjapanzer** [comment]
I will look at this over lunch today

**Comment by ninjapanzer** [comment]
I think we can set off the text by just changing the color. I think the change in weight makes this feel very different than the rest of the sections. The rest of it looks fine @Arevyn24

**Comment by Arevyn24** [comment]
@ninjapanzer font weight FEEXED 
image

**Pull request merged**
